export type BibleBookMeta = {
  id: string;
  name: string;
  testament: "Ancien Testament" | "Nouveau Testament";
  chapters: number;
};

export const bibleBooks: BibleBookMeta[] = [
  { id: "gen", name: "Genèse", testament: "Ancien Testament", chapters: 50 },
  { id: "exo", name: "Exode", testament: "Ancien Testament", chapters: 40 },
  { id: "lev", name: "Lévitique", testament: "Ancien Testament", chapters: 27 },
  { id: "num", name: "Nombres", testament: "Ancien Testament", chapters: 36 },
  { id: "deu", name: "Deutéronome", testament: "Ancien Testament", chapters: 34 },
  { id: "jos", name: "Josué", testament: "Ancien Testament", chapters: 24 },
  { id: "jdg", name: "Juges", testament: "Ancien Testament", chapters: 21 },
  { id: "rut", name: "Ruth", testament: "Ancien Testament", chapters: 4 },
  { id: "1sa", name: "1 Samuel", testament: "Ancien Testament", chapters: 31 },
  { id: "2sa", name: "2 Samuel", testament: "Ancien Testament", chapters: 24 },
  { id: "1ki", name: "1 Rois", testament: "Ancien Testament", chapters: 22 },
  { id: "2ki", name: "2 Rois", testament: "Ancien Testament", chapters: 25 },
  { id: "1ch", name: "1 Chroniques", testament: "Ancien Testament", chapters: 29 },
  { id: "2ch", name: "2 Chroniques", testament: "Ancien Testament", chapters: 36 },
  { id: "ezr", name: "Esdras", testament: "Ancien Testament", chapters: 10 },
  { id: "neh", name: "Néhémie", testament: "Ancien Testament", chapters: 13 },
  { id: "est", name: "Esther", testament: "Ancien Testament", chapters: 10 },
  { id: "job", name: "Job", testament: "Ancien Testament", chapters: 42 },
  { id: "psa", name: "Psaumes", testament: "Ancien Testament", chapters: 150 },
  { id: "pro", name: "Proverbes", testament: "Ancien Testament", chapters: 31 },
  { id: "ecc", name: "Ecclésiaste", testament: "Ancien Testament", chapters: 12 },
  { id: "sng", name: "Cantique des Cantiques", testament: "Ancien Testament", chapters: 8 },
  { id: "isa", name: "Ésaïe", testament: "Ancien Testament", chapters: 66 },
  { id: "jer", name: "Jérémie", testament: "Ancien Testament", chapters: 52 },
  { id: "lam", name: "Lamentations", testament: "Ancien Testament", chapters: 5 },
  { id: "ezk", name: "Ézéchiel", testament: "Ancien Testament", chapters: 48 },
  { id: "dan", name: "Daniel", testament: "Ancien Testament", chapters: 12 },
  { id: "hos", name: "Osée", testament: "Ancien Testament", chapters: 14 },
  { id: "joe", name: "Joël", testament: "Ancien Testament", chapters: 3 },
  { id: "amo", name: "Amos", testament: "Ancien Testament", chapters: 9 },
  { id: "oba", name: "Abdias", testament: "Ancien Testament", chapters: 1 },
  { id: "jon", name: "Jonas", testament: "Ancien Testament", chapters: 4 },
  { id: "mic", name: "Michée", testament: "Ancien Testament", chapters: 7 },
  { id: "nah", name: "Nahum", testament: "Ancien Testament", chapters: 3 },
  { id: "hab", name: "Habacuc", testament: "Ancien Testament", chapters: 3 },
  { id: "zep", name: "Sophonie", testament: "Ancien Testament", chapters: 3 },
  { id: "hag", name: "Aggée", testament: "Ancien Testament", chapters: 2 },
  { id: "zec", name: "Zacharie", testament: "Ancien Testament", chapters: 14 },
  { id: "mal", name: "Malachie", testament: "Ancien Testament", chapters: 4 },
  { id: "mat", name: "Matthieu", testament: "Nouveau Testament", chapters: 28 },
  { id: "mrk", name: "Marc", testament: "Nouveau Testament", chapters: 16 },
  { id: "luk", name: "Luc", testament: "Nouveau Testament", chapters: 24 },
  { id: "jhn", name: "Jean", testament: "Nouveau Testament", chapters: 21 },
  { id: "act", name: "Actes", testament: "Nouveau Testament", chapters: 28 },
  { id: "rom", name: "Romains", testament: "Nouveau Testament", chapters: 16 },
  { id: "1co", name: "1 Corinthiens", testament: "Nouveau Testament", chapters: 16 },
  { id: "2co", name: "2 Corinthiens", testament: "Nouveau Testament", chapters: 13 },
  { id: "gal", name: "Galates", testament: "Nouveau Testament", chapters: 6 },
  { id: "eph", name: "Éphésiens", testament: "Nouveau Testament", chapters: 6 },
  { id: "phi", name: "Philippiens", testament: "Nouveau Testament", chapters: 4 },
  { id: "col", name: "Colossiens", testament: "Nouveau Testament", chapters: 4 },
  { id: "1th", name: "1 Thessaloniciens", testament: "Nouveau Testament", chapters: 5 },
  { id: "2th", name: "2 Thessaloniciens", testament: "Nouveau Testament", chapters: 3 },
  { id: "1ti", name: "1 Timothée", testament: "Nouveau Testament", chapters: 6 },
  { id: "2ti", name: "2 Timothée", testament: "Nouveau Testament", chapters: 4 },
  { id: "tit", name: "Tite", testament: "Nouveau Testament", chapters: 3 },
  { id: "phm", name: "Philémon", testament: "Nouveau Testament", chapters: 1 },
  { id: "heb", name: "Hébreux", testament: "Nouveau Testament", chapters: 13 },
  { id: "jas", name: "Jacques", testament: "Nouveau Testament", chapters: 5 },
  { id: "1pe", name: "1 Pierre", testament: "Nouveau Testament", chapters: 5 },
  { id: "2pe", name: "2 Pierre", testament: "Nouveau Testament", chapters: 3 },
  { id: "1jn", name: "1 Jean", testament: "Nouveau Testament", chapters: 5 },
  { id: "2jn", name: "2 Jean", testament: "Nouveau Testament", chapters: 1 },
  { id: "3jn", name: "3 Jean", testament: "Nouveau Testament", chapters: 1 },
  { id: "jud", name: "Jude", testament: "Nouveau Testament", chapters: 1 },
  { id: "rev", name: "Apocalypse", testament: "Nouveau Testament", chapters: 22 },
];
